name: 'TestPlugin'
main: 'com.ryderbelserion.vital.TestPlugin'

version: '1.0'
api-version: '1.20'
description: 'A description'
website: 'a website'

folia-supported: true

dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    FancyHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    CMI:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true